Add origin/destination on departures/arrivals
public-transport/hafas-client pull request #260
Opened 2022-02-07 21:24 UTC by bddq

I renamed `direction/provenance` properties to `headsign` and added a more complete info on `origin/destination` property if available.

This will help to close issue #259.

2022-02-18 16:29 UTC, derhuerst requested changes
Thanks for the PR!

While this PR contributes a very useful piece of information to `departures()`/`arrivals()`, as of now, the `headsign` renaming is a breaking change, so I can't merge it into the `master`/`5` branches. I'd happily merge the `destination`/`origin` part though.

2022-02-18 16:29 UTC, derhuerst commented on parse/arrival-or-departure.js
> +			headsign: d.dirTxt && profile.parseStationName(ctx, d.dirTxt) || null,
Removing a field, or changing its type signature (e.g. from "string or `null`" to "stop object or `null`") is considered a breaking change in `hafas-client`.

2022-02-18 16:29 UTC, derhuerst commented on parse/arrival-or-departure.js
> +			res.destination = profile.parseLocation(ctx, ctx.res.common.locL[d.prodL[0].tLocX])
Wow! You have discovered an aspect of the HAFAS mgate.exe response format that I didn't know about, even though I have worked with/against it for quite a while now. 🎉 

We should double-check if this actually *always* is the destination/origin (whatever that exactly means, there are lots of nuanced cases where the notion of a terminus stop is not so clear). **As `tLocX` usually specifies the stop that a certain *product* runs to, we need to check what happens with trips that change their *product* along their course, e.g. in-seat-transfer or shuttle buses.**

If `tLocX` turns out to be consistent with what one would consider the destination of a departing trip, let's merge it!

2022-02-18 16:34 UTC, derhuerst commented
About the `headsign` renaming: Unfortunately, the `dirTxt` *is not* the headsign (as in the text used to identify the trip/route, usually displayed on the vehicle), because for regular scheduled (non-shuttle, non-replacement-service, etc.) trips, it usually contains the *direction*, but with arrivals, it contains the *origin*. See https://github.com/public-transport/hafas-client/issues/179#issuecomment-641178783 for details.

2022-02-18 21:09 UTC, bddq commented
@derhuerst I reverted `headsign` breaking change.

2022-02-19 20:52 UTC, derhuerst commented on test/e2e/lib/validators.js
> +        if (type === 'departure') {
Can you convert these lines to tabs, which are used in the `hafas-client` code base. This will also make the diff more "focused".

2022-02-19 20:53 UTC, derhuerst approved these changes
This looks good. Let me check what HAFAS returns in the special cases mentioned above.

2022-02-19 21:09 UTC, derhuerst commented
If you have time for it, you can adapt >=1 of the following `parseDepartures`/`departures()` tests (whose fixtures contain `tLocX`/`fLocX`) to check if `destination` is being parsed:

- [`test/vbb-departures.js`](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/test/vbb-departures.js#L24-L31) ([fixture](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/test/fixtures/vbb-departures.json))
- [`test/vsn-departures.js`](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/test/vsn-departures.js#L31-L38) ([fixture](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/test/fixtures/vsn-departures.json))

Otherwise I can do it as well.

2022-02-19 23:21 UTC, derhuerst commented
Looking at a trip [through-serviced](https://en.wikipedia.org/wiki/Through_service) with another trip of a different route/line, we can see that **`locL[tLocX]` represents the last stop of the through-serviced trip**:

```shell
./tools/debug-cli/cli.js vbb departures 900000009102 | jq '.[] | [.tripId, .line.name, .direction, .destination]'
```

```json
[
	"1|68827|2|86|19022022",
	"120",
	"S+U Wittenau -> Bus 220",
	{
		"type": "stop",
		"id": "900000092202",
		"name": "Hainbuchenstr.",
		"location": {
			"type": "location",
			"id": "900092202",
			"latitude": 52.634251,
			"longitude": 13.27482
		},
		"products": {
			"suburban": false,
			"subway": false,
			"tram": false,
			"bus": true,
			"ferry": false,
			"express": false,
			"regional": false
		}
	}
]
```

When querying such trips, HAFAS returns includes the stopovers of the respective through-serviced 2nd trip in `.stopL[]` and adds a remark at the stopover where the route/line changes:

```shell
./tools/debug-cli/cli.js vbb trip '1|68827|2|86|19022022' '120' | jq
```

```json
{
	"id": "1|68827|2|86|19022022",
	"reachable": true,
	"line": {
		"type": "line",
		"id": "120",
		"fahrtNr": "2876",
		"name": "120",
		"public": true,
		"adminCode": "BVB",
		"productName": "Bus",
		"mode": "bus",
		"product": "bus",
		"operator": {
			"type": "operator",
			"id": "berliner-verkehrsbetriebe",
			"name": "Berliner Verkehrsbetriebe"
		},
		"symbol": null,
		"nr": 120,
		"metro": false,
		"express": false,
		"night": false
	},
	"direction": "S+U Wittenau -> Bus 220",
	"currentLocation": {
		"type": "location",
		"latitude": 52.537815,
		"longitude": 13.372821
	},

	"origin": {
		"type": "stop",
		"id": "900000002255",
		"name": "Seydlitzstr.",
		"location": {
			"type": "location",
			"id": "900002255",
			"latitude": 52.527037,
			"longitude": 13.364155
		}
	},
	"departure": "2022-02-19T22:15:00+01:00",
	"plannedDeparture": "2022-02-19T22:15:00+01:00",
	"departureDelay": 0,

	"destination": {
		"type": "stop",
		"id": "900000092202",
		"name": "Hainbuchenstr.",
		"location": {
			"type": "location",
			"id": "900092202",
			"latitude": 52.634251,
			"longitude": 13.27482
		}
	},
	"arrival": "2022-02-19T23:07:00+01:00",
	"plannedArrival": "2022-02-19T23:06:00+01:00",
	"arrivalDelay": 60,

	"stopovers": [
		{
			"stop": {
				"type": "stop",
				"id": "900000002255",
				"name": "Seydlitzstr.",
				"location": {
					"type": "location",
					"id": "900002255",
					"latitude": 52.527037,
					"longitude": 13.364155
				}
			},
			"arrival": null,
			"plannedArrival": null,
			"arrivalDelay": null,
			"departure": "2022-02-19T22:15:00+01:00",
			"plannedDeparture": "2022-02-19T22:15:00+01:00",
			"departureDelay": 0,
			"remarks": [
				{
					"type": "hint",
					"code": "text.journeystop.product.or.direction.changes.stop.message",
					"text": "Verkehrt ab hier als 120 in Richtung S+U Wittenau -> Bus 220"
				}
			]
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000001204",
				"name": "Lehrter Str./Invalidenstr.",
				"location": {
					"type": "location",
					"id": "900001204",
					"latitude": 52.52576,
					"longitude": 13.365225
				},
				"products": {
					"suburban": false,
					"subway": false,
					"tram": true,
					"bus": true,
					"ferry": false,
					"express": false,
					"regional": false
				}
			},
			"arrival": "2022-02-19T22:16:00+01:00",
			"plannedArrival": "2022-02-19T22:16:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:16:00+01:00",
			"plannedDeparture": "2022-02-19T22:16:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000003201",
				"name": "S+U Berlin Hauptbahnhof",
				"location": {
					"type": "location",
					"id": "900003201",
					"latitude": 52.525607,
					"longitude": 13.369072
				},
				"products": {
					"suburban": true,
					"subway": true,
					"tram": true,
					"bus": true,
					"ferry": false,
					"express": true,
					"regional": true
				}
			},
			"arrival": "2022-02-19T22:17:00+01:00",
			"plannedArrival": "2022-02-19T22:17:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:17:00+01:00",
			"plannedDeparture": "2022-02-19T22:17:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000100503",
				"name": "Invalidenpark",
				"location": {
					"type": "location",
					"id": "900100503",
					"latitude": 52.528762,
					"longitude": 13.376929
				},
				"products": {
					"suburban": false,
					"subway": false,
					"tram": true,
					"bus": true,
					"ferry": false,
					"express": false,
					"regional": false
				}
			},
			"arrival": "2022-02-19T22:18:00+01:00",
			"plannedArrival": "2022-02-19T22:18:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:18:00+01:00",
			"plannedDeparture": "2022-02-19T22:18:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000100502",
				"name": "Habersaathstr.",
				"location": {
					"type": "location",
					"id": "900100502",
					"latitude": 52.530533,
					"longitude": 13.374052
				}
			},
			"arrival": "2022-02-19T22:19:00+01:00",
			"plannedArrival": "2022-02-19T22:19:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:19:00+01:00",
			"plannedDeparture": "2022-02-19T22:19:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000100035",
				"name": "Bundeswehrkrankenhaus",
				"location": {
					"type": "location",
					"id": "900100035",
					"latitude": 52.534686,
					"longitude": 13.370088
				}
			},
			"arrival": "2022-02-19T22:20:00+01:00",
			"plannedArrival": "2022-02-19T22:20:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:20:00+01:00",
			"plannedDeparture": "2022-02-19T22:20:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000008193",
				"name": "Boyenstr.",
				"location": {
					"type": "location",
					"id": "900008193",
					"latitude": 52.536925,
					"longitude": 13.370888
				}
			},
			"arrival": "2022-02-19T22:21:00+01:00",
			"plannedArrival": "2022-02-19T22:21:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:21:00+01:00",
			"plannedDeparture": "2022-02-19T22:21:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000008102",
				"name": "U Reinickendorfer Str.",
				"location": {
					"type": "location",
					"id": "900008102",
					"latitude": 52.539891,
					"longitude": 13.370385
				},
				"products": {
					"suburban": false,
					"subway": true,
					"tram": false,
					"bus": true,
					"ferry": false,
					"express": false,
					"regional": false
				}
			},
			"arrival": "2022-02-19T22:22:00+01:00",
			"plannedArrival": "2022-02-19T22:22:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:22:00+01:00",
			"plannedDeparture": "2022-02-19T22:22:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000009104",
				"name": "S+U Wedding",
				"location": {
					"type": "location",
					"id": "900009104",
					"latitude": 52.542732,
					"longitude": 13.366061
				},
				"products": {
					"suburban": true,
					"subway": true,
					"tram": false,
					"bus": true,
					"ferry": false,
					"express": false,
					"regional": false
				}
			},
			"arrival": "2022-02-19T22:23:00+01:00",
			"plannedArrival": "2022-02-19T22:23:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:23:00+01:00",
			"plannedDeparture": "2022-02-19T22:23:00+01:00",
			"departureDelay": 0
		},
		{
			"stop": {
				"type": "stop",
				"id": "900000009151",
				"name": "Gerichtstr.",
				"location": {
					"type": "location",
					"id": "900009151",
					"latitude": 52.544476,
					"longitude": 13.362663
				}
			},
			"arrival": "2022-02-19T22:24:00+01:00",
			"plannedArrival": "2022-02-19T22:24:00+01:00",
			"arrivalDelay": 0,
			"departure": "2022-02-19T22:24:00+01:00",
			"plannedDeparture": "2022-02-19T22:24:00+01:00",
 [...]

2022-02-20 20:41 UTC, bddq commented
I understand your point of view about through-serviced trips. 

I think your example illustrate that client apps should present remarks on a trip to help user to understand what changes during the journey.

As seen on the DB Navigator app, I will take Bus 120 from Seydlitzstr. to Hainbuchenstr. with a user info that bus number will change from Wittenau to destination.

From my point of view this is not a problem to display through-serviced trips with the full trip stop references for origin/destination and relying on remarks to display the right info to the user.

2022-02-20 23:46 UTC, derhuerst commented
In an ideal world, I think it should be the other way around:

- If I query departures at a stop, I'm often not interested in the through-serviced trip after the departing one, but rather, if I'm about to board the right vehicle.
- Given my destination, if it makes sense to make use of the through-serviced trip by staying in the vehicle, a routing should tell me this!
- If I know the area well enough or am into "manual/human routing" (deciding on an itinerary by checking all the options), I might know about the through-servicing or at least recognise it in the remarks.

But: If we decide to a) move the through-serviced stopovers of a trip returned by `trip()` into a separate field, and b) keep the through-serviced `destination` in the corresponding `departures()` result, I'd say that would be really inconsistent.

I therefore think that we have the choice: Does `hafas-client` try to be more developer-/user-friendly by abstracting away some of the design & technical limitations of HAFAS, at the cost of inconsistent abstractions? Or should it represent whatever it has fetched in a raw & "authentic" way?

Given that the former hasn't worked out very well for `hafas-client` so far (`provenance`/`direction` are not 100% semantically precise, `.line` fits neither FPTF nor HAFAS semantically, etc.), **I have decided to merge your PR and *don't* split through-serviced stopovers from a trip.**

2022-02-21 10:44 UTC, closed without merging

2022-02-21 10:45 UTC, derhuerst commented
I have squash-merged your PR and amended a few fixes in the tests.

2022-02-21 10:46 UTC, derhuerst commented
Do you want to mentioned as a contributor in `package.json`? If yes, with which signature? `bddq `?

2022-02-21 15:10 UTC, bddq commented
> Do you want to mentioned as a contributor in `package.json`? If yes, with which signature? `bddq `?

Thanks. You can put `Benoit Deldicque (https://github.com/bddq)`.